### ISSUE TITLE
InvalidOperationException: Collection was modified; enumeration operation may not execute.

### ISSUE THREAD

**Issue by codemonkeynorth** [PyroGreg8/Unity-Type-Based-Event-Manager#1]
Hi @greghornby 

Useful script thank you. I'm not sure the exact chain of events that causes this currently but I get an error here
https://github.com/greghornby/Unity-Type-Based-Event-Manager/blob/master/EventManager.cs#L72

I'm assuming it's related to `DynamicInvoke` but somehow the list changes during processing giving this error
`InvalidOperationException: Collection was modified; enumeration operation may not execute.`

the solution seems to be to cast the `listeners` to an Array so it's not iterating a list that can change, but a copy instead. 
`foreach (var listener in listeners).ToArray())`

this is discussed here...
https://www.tutorialspoint.com/why-the-error-collection-was-modified-enumeration-operation-may-not-execute-occurs-and-how-to-handle-it-in-chash
https://stackoverflow.com/questions/29587056/c-sharp-collection-was-modified-enumeration-operation-may-not-execute

I'll see if I can put together a simple example to demonstrate the problem, but most likely it's down to the `DynamicInvoke` callback causing my listener to be removed or another to be added (in another part of my application) before that iteration of the loop is complete

thanks

**Comment by greghornby** [comment]
Hello! I haven't touched Unity or C# in a number of years. Would this change to the `TriggerEvent` method work? Would you be able to test it?

```
public static void TriggerEvent<T>(T data) {
    CheckSceneMatches();
    List<Delegate> listeners = null;
    if (eventDictionary.TryGetValue (typeof(T), out listeners)) {
        Delegate[] listenersStatic = listeners.ToArray();
        foreach (var listener in listenersStatic) {
            listener.DynamicInvoke(data);
        }
    }
}
```

**Comment by codemonkeynorth** [comment]
@greghornby hi thanks for the reply. 

I skipped the `Delgate[] listenersStatic` line and just used it directly:

` foreach (var listener in listeners.ToArray())`

(it's not trying to reassign the array back to `listeners` so it's the same thing)

but yes that fixes it.

J.
